rule samtools_sort:
	input:
		bam = "/biarchive/project/jhshin/test/snakemake_totorial/test_data/{sample}.bam"
	output:
		bam = "/biarchive/project/jhshin/test/snakemake_totorial/test_data/{sample}.sorted.bam"
	params: 
		thread = 8
	shell:
		"samtools sort -@ {params.thread} -T {wildcards.sample} "
		"-O bam {input.bam} > {output.bam}"
